# Generated by Django 3.1.7 on 2021-04-24 12:20

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bookmarksapp', '0002_bookmark_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
